const Course = require("../models/Course");

const seedCourses = [
  {
    title: "Complete Web Development Bootcamp",
    instructor: "Sarah Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    rating: 4.8,
    reviews: 15420,
    students: 52300,
    durationHours: 40,
    lessons: 285,
    price: 99.99,
    originalPrice: 199.99,
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Web Development",
    bestseller: true,
    description: "Master HTML, CSS, JavaScript, React, and Node.js from scratch with hands-on projects.",
  },
  {
    title: "Advanced React & TypeScript",
    instructor: "Michael Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael",
    rating: 4.9,
    reviews: 12350,
    students: 38900,
    durationHours: 35,
    lessons: 220,
    price: 129.99,
    originalPrice: 249.99,
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop",
    level: "Advanced",
    category: "Web Development",
    bestseller: false,
    description: "Build production-grade React apps with TypeScript, hooks, and modern patterns.",
  },
  {
    title: "UI/UX Design Masterclass",
    instructor: "Emma Davis",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    rating: 4.7,
    reviews: 9870,
    students: 28500,
    durationHours: 28,
    lessons: 185,
    price: 89.99,
    originalPrice: 179.99,
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Design",
    bestseller: false,
    description: "Learn user research, wireframing, prototyping, and design systems in Figma.",
  },
  {
    title: "Python for Data Science",
    instructor: "David Martinez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david",
    rating: 4.9,
    reviews: 18200,
    students: 62100,
    durationHours: 45,
    lessons: 310,
    price: 119.99,
    originalPrice: 229.99,
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Data Science",
    bestseller: true,
    description: "Analyze data with Pandas, visualize with Matplotlib, and build ML models with scikit-learn.",
  },
  {
    title: "Mobile App Development with React Native",
    instructor: "Lisa Anderson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lisa",
    rating: 4.6,
    reviews: 8450,
    students: 25300,
    durationHours: 32,
    lessons: 195,
    price: 109.99,
    originalPrice: 199.99,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Mobile Development",
    bestseller: false,
    description: "Create cross-platform mobile apps for iOS and Android using React Native.",
  },
  {
    title: "Machine Learning A-Z",
    instructor: "James Wilson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
    rating: 4.8,
    reviews: 14700,
    students: 48200,
    durationHours: 42,
    lessons: 275,
    price: 134.99,
    originalPrice: 259.99,
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop",
    level: "Advanced",
    category: "AI & Machine Learning",
    bestseller: true,
    description: "Deep dive into supervised and unsupervised learning, neural networks, and deployment.",
  },
  {
    title: "Node.js & Express Backend Mastery",
    instructor: "Alex Turner",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    rating: 4.7,
    reviews: 7200,
    students: 19800,
    durationHours: 24,
    lessons: 160,
    price: 79.99,
    originalPrice: 149.99,
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Web Development",
    bestseller: false,
    description: "Build REST APIs, authenticate users, and connect to MongoDB with Express.",
  },
  {
    title: "Digital Marketing Fundamentals",
    instructor: "Rachel Green",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rachel",
    rating: 4.5,
    reviews: 5600,
    students: 17200,
    durationHours: 18,
    lessons: 120,
    price: 59.99,
    originalPrice: 119.99,
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Marketing",
    bestseller: false,
    description: "SEO, social media marketing, email campaigns, and analytics for beginners.",
  },
  {
    title: "Flutter & Dart: Complete Guide",
    instructor: "Priya Sharma",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    rating: 4.6,
    reviews: 6800,
    students: 21500,
    durationHours: 30,
    lessons: 200,
    price: 94.99,
    originalPrice: 189.99,
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Mobile Development",
    bestseller: false,
    description: "Build beautiful native mobile apps with Flutter and the Dart programming language.",
  },
  {
    title: "Deep Learning with TensorFlow",
    instructor: "Robert Kim",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=robert",
    rating: 4.8,
    reviews: 9100,
    students: 28400,
    durationHours: 38,
    lessons: 240,
    price: 124.99,
    originalPrice: 239.99,
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=225&fit=crop",
    level: "Advanced",
    category: "AI & Machine Learning",
    bestseller: true,
    description: "Neural networks, CNNs, RNNs, and transfer learning with TensorFlow 2.",
  },
  {
    title: "Figma for UI Designers",
    instructor: "Nina Patel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nina",
    rating: 4.7,
    reviews: 4300,
    students: 14800,
    durationHours: 14,
    lessons: 95,
    price: 49.99,
    originalPrice: 99.99,
    thumbnail: "https://images.unsplash.com/photo-1586717791827-3f44a563fa4c?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Design",
    bestseller: false,
    description: "Master Figma tools, components, auto-layout, and collaborative design workflows.",
  },
  {
    title: "SQL & Database Design",
    instructor: "Tom Bradley",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tom",
    rating: 4.6,
    reviews: 11200,
    students: 35600,
    durationHours: 22,
    lessons: 150,
    price: 69.99,
    originalPrice: 139.99,
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Data Science",
    bestseller: false,
    description: "Write complex queries, design normalized schemas, and optimize database performance.",
  },
  {
    title: "AWS Cloud Practitioner",
    instructor: "Karen White",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=karen",
    rating: 4.5,
    reviews: 8900,
    students: 31200,
    durationHours: 20,
    lessons: 130,
    price: 84.99,
    originalPrice: 169.99,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Web Development",
    bestseller: false,
    description: "Prepare for the AWS certification with EC2, S3, Lambda, and cloud architecture basics.",
  },
  {
    title: "Content Strategy & Copywriting",
    instructor: "Olivia Brown",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=olivia",
    rating: 4.4,
    reviews: 3200,
    students: 9800,
    durationHours: 12,
    lessons: 80,
    price: 39.99,
    originalPrice: 79.99,
    thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400&h=225&fit=crop",
    level: "Beginner",
    category: "Marketing",
    bestseller: false,
    description: "Craft compelling copy, build content calendars, and grow audiences organically.",
  },
  {
    title: "Cybersecurity Essentials",
    instructor: "Mark Stevens",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mark",
    rating: 4.7,
    reviews: 6400,
    students: 18900,
    durationHours: 26,
    lessons: 175,
    price: 99.99,
    originalPrice: 199.99,
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=225&fit=crop",
    level: "Intermediate",
    category: "Web Development",
    bestseller: false,
    description: "Network security, encryption, penetration testing, and secure coding practices.",
  },
];

async function seedDatabase() {
  const count = await Course.countDocuments();
  if (count === 0) {
    await Course.insertMany(seedCourses);
    console.log(`Seeded ${seedCourses.length} courses`);
  } else {
    console.log(`Database already has ${count} courses, skipping seed`);
  }
}

module.exports = { seedCourses, seedDatabase };
